version: "2.0"
nlu:
- intent: book_appointment
  examples: |
    - എനിക്കൊരു അപ്പോയിന്റ് മെന്റ് വേണം .
    - എനിക്കൊരു അപ്പോയിന്റ് മെന്റ് എടുക്കണം .
    - ഒരു അപ്പോയിന്റ് മെന്റ് ബുക്ക് ചെയ്യുക
- intent: bye
  examples: |
    - ശരി എന്നാ
- intent: centre_contact
  examples: |
    - എന്താണ് ഹെൽത്ത് സെന്റർ ഫോൺ നമ്പർ ?
- intent: centre_timings
  examples: |
    - ഹെൽത്ത് സെന്ററിന്റെ സമയങ്ങൾ
    - എപ്പോഴാണ് സെന്റർ അടയ്ക്കുന്നത്?
    - സെന്റർ തുറന്നോ?
    - എപ്പോഴാണ് ഹെൽത്ത് കെയർ സെന്റർ തുറക്കുന്നത് ?
    - സെന്റർ അടച്ചോ?
    - ഹെൽത്ത് സെന്റർ അടച്ചോ?
    - ഹെൽത്ത് സെന്റർ തുറന്നോ?
    - ഹെൽത്ത് കെയർ സെന്റർ തുറന്നോ?
- intent: doctor_contact
  examples: |
    - എന്താണ് ഡോക്ടറുടെ ഫോൺ നമ്പർ ?
- intent: doctor_timings
  examples: |
    - ഡോക്ടർ അവിടെയുണ്ടോ ?
    - ഡോക്ടർ ഇപ്പോൾ ഉണ്ടോ ?
    - ഡോക്ടറുടെ സമയം
    - അവിടെ ഡോക്ടർ ഉണ്ടോ ?
    - എനിക്ക് ഡോക്ടറെ കാണണം .
- intent: greet
  examples: |
    - ഹലോ
    - ഹൈ
- intent: help
  examples: |
    - സഹായം ആവശ്യമാണ്
    - എനിക്ക് സഹായം വേണം
- intent: symptoms
  examples: |
    - എനിക്ക് പനിയും ചുമയും ഉണ്ട്
    - എനിക്ക് കൈവേദനയുണ്ട്
    - എനിക്ക് മൂക്കൊലിപ്പ് ഉണ്ട്
    - എനിക്ക് തൊണ്ടവേദനയുണ്ട്
    - എനിക്ക് പനിയുണ്ട്
    - മാനസിക വിഷാദം
- intent: thank
  examples: |
    - വളരെ നന്ദി
    - നന്ദി നമസ്കാരം
