version: "3.9"
services:
  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - ${MONGO_EXPRESS_EXTERNAL_PORT}:8081
    depends_on:
      - mongo
  rasa:
    volumes:
      - .:/app
    entrypoint: ""
    command: ""
    depends_on:
      - mongo
volumes:
  mongodb: