version: "3.9"
services:
  rasa:
    environment: 
      HOME: "/tmp"
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/app:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - ${RASA_EXTERNAL_DEBUG_PORT}:5005
